# Generated by Django 3.2.2 on 2021-06-03 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Arduino', models.CharField(max_length=8)),
                ('dia', models.DateTimeField(default=datetime.datetime.now)),
                ('latitud', models.CharField(max_length=50)),
                ('longitud', models.CharField(max_length=50)),
                ('temperatura', models.CharField(max_length=50)),
                ('pressio', models.CharField(max_length=50)),
                ('pluja', models.CharField(max_length=50)),
                ('humitat_aire', models.CharField(max_length=50)),
                ('humitat_terrestre', models.CharField(max_length=50)),
                ('velocitat_vent', models.CharField(max_length=50)),
                ('direccio_vent', models.CharField(max_length=50)),
            ],
        ),
    ]
