# Generated by Django 3.2.2 on 2021-06-10 11:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arduino',
            fields=[
                ('id_station', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('model_arduino', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=50)),
                ('lon', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(default=datetime.datetime.now)),
                ('temperature', models.CharField(max_length=50)),
                ('press', models.CharField(max_length=50)),
                ('rain', models.CharField(max_length=50)),
                ('air_humidity', models.CharField(max_length=50)),
                ('wind_speed', models.CharField(max_length=50)),
                ('wind_direction', models.CharField(max_length=50)),
                ('id_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.arduino')),
            ],
        ),
    ]
